//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateEncryptionDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseEncryptionLog
    {
        public int ID { get; set; }
        public string EncryptionStatus { get; set; }
        public string Application { get; set; }
        public string LastUpdate { get; set; }
        public Nullable<int> Tally { get; set; }
    }
}
