//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateEncryptionDashboard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntities1 : DbContext
    {
        public DataEntities1()
            : base("name=DataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DatabaseEncryptionLogTest> DatabaseEncryptionLogTests { get; set; }
        public DbSet<statusSQLTest> statusSQLTests { get; set; }
        public DbSet<DatabaseEncryptionLog> DatabaseEncryptionLogs { get; set; }
        public DbSet<statusSQL> statusSQLs { get; set; }
    }
}
