//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateEncryptionDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class statusSQLTest
    {
        public int id { get; set; }
        public string NodeName { get; set; }
        public string Instance { get; set; }
        public string DBname { get; set; }
        public string LogicalFileName { get; set; }
        public string PathFromSQL { get; set; }
        public string FileType { get; set; }
        public string NodeNameVormetric { get; set; }
        public string GuardPointPath { get; set; }
        public string EncryptionStatus { get; set; }
        public string Application { get; set; }
        public string State { get; set; }
        public string Environment { get; set; }
        public string LastUpdate { get; set; }
    }
}
